#!/usr/bin/env bash

export COOKER_BUSY_PERIOD=0.0
export COOKER_BUSY_PROCESSES=0
export COOKER_CPU_LIMIT=150m
export COOKER_CPU_REQUEST=150m
export COOKER_MEMORY_LIMIT=10Mi
export COOKER_MEMORY_REQUEST=10Mi
export COOKER_NUM_PODS=10
export COOKER_PRE_BUSY_SLEEP_S=120.0
export COOKER_USE_MEMORY_M=0
