---

# The PyKubePressureCooker Deployment Configuration template.
#
# To load:   oc process -f cooker.yml | oc create -f -
# To unload: oc delete all --selector template=pressure-cooker
#
# To give cluster-admin to the default service account and avoid the
# API error:
#   system:serviceaccount:cooker-pot:default
#      cannot create jobs.batch in project cooker-pot
# Run the following command as system:admin...
#
# oc adm policy add-cluster-role-to-user cluster-admin -z default

kind: Template
apiVersion: v1
metadata:
  name: pressure-cooker
  annotations:
    description: The PyKubePressureCooker Application
    tags: pressure-cooker
labels:
  template: pressure-cooker

# -----------------------------------------------------------------------------

parameters:

  - name: IMAGE_NAME
    value: pykubepressurecooker
    description: >
      The name of the template application.
      This is not normally changed but is a parameter because it
      is used in several places in the template.

  - name: OWNER
    value: alanbchristie
    description: >
      The GitLab user or group the image belongs to.
      In our case this is the MatildaPeak group of repositories.

  - name: TAG
    value: 'latest'
    description: >
      The Docker image tag for the container image

  - name: BUSY_PERIOD
    value: '0.0'
  - name: BUSY_PROCESSES
    value: '0'
  - name: CPU_LIMIT
    value: '150m'
  - name: CPU_REQUEST
    value: '150m'
  - name: MEMORY_LIMIT
    value: '10Mi'
  - name: MEMORY_REQUEST
    value: '10Mi'
  - name: NUM_PODS
    value: '10'
  - name: PRE_BUSY_SLEEP_S
    value: '120.0'
  - name: USE_MEMORY_M
    value: '0'

# -----------------------------------------------------------------------------

objects:

  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: ${{IMAGE_NAME}}
    annotations:
      description: >
        The Pressure Cooker deployment
    spec:
      replicas: 1
      selector:
        name: ${{IMAGE_NAME}}
      template:
        metadata:
          labels:
            name: ${{IMAGE_NAME}}
        spec:
          containers:
          - image: ${OWNER}/${IMAGE_NAME}:${TAG}
            name: ${{IMAGE_NAME}}
            env:
            - name: COOKER_BUSY_PERIOD
              value: ${BUSY_PERIOD}
            - name: COOKER_BUSY_PROCESSES
              value: ${BUSY_PROCESSES}
            - name: COOKER_CPU_LIMIT
              value: ${CPU_LIMIT}
            - name: COOKER_CPU_REQUEST
              value: ${CPU_REQUEST}
            - name: COOKER_MEMORY_LIMIT
              value: ${MEMORY_LIMIT}
            - name: COOKER_MEMORY_REQUEST
              value: ${MEMORY_REQUEST}
            - name: COOKER_NUM_PODS
              value: ${NUM_PODS}
            - name: COOKER_PRE_BUSY_SLEEP_S
              value: ${PRE_BUSY_SLEEP_S}
            - name: COOKER_USE_MEMORY_M
              value: ${USE_MEMORY_M}
            resources:
              limits:
                cpu: 1000m
                memory: 2Gi
